### ISSUE TITLE
Where to find Grammar written in ANTRL for Common Workflow Language?

### ISSUE THREAD

**Issue by DeepakArora76** [alpha-unito/streamflow#12]
I would appreciate it if you could share a link to the grammar, lex and parser, written using the Antrl framework for CWL.

**Comment by GlassOfWhiskey** [comment]
Hi @DeepakArora76,
unfortunately I am not aware of any ANTLR parser for CWL grammar.
The only ANTLR parser used in StreamFlow is for EcmaScript 6 (JavaScript) and it is used to statically check CWL Expression to identify input dependencies.
My suggestion is to ask on the [discourse group](https://cwl.discourse.group/) if someone in the CWL community is aware of an ANTLR parser.
