### ISSUE TITLE
Used in production? Status of CWL v1.{0,1,2} conformance tests?

### ISSUE THREAD

**Issue by mr-c** [alpha-unito/streamflow#8]
Thank you for https://github.com/mr-c/cwl_methods_included/issues/3 ; as for the listing of Streamflow on the CWL website under https://www.commonwl.org/#Implementations I was curious if we should move it up from "Partial Implementations"

Is Streamflow used in production? Please list where and by whom. 

How many CWL v1.0, v1.1, and v1.2 conformance tests pass? Which optional features of CWL does it support?

Consider generated CWL conformance badges to better communicate what parts of the CWL standards you support: https://github.com/common-workflow-language/cwltest#generate-conformance-badges-using-cwltest 
(Example: https://github.com/tom-tan/ep3/releases/tag/v1.7.0 )

**Comment by GlassOfWhiskey** [comment]
Hi Michael,
StreamFlow reached its Beta phase with version 0.1.0 and supports all required features of CWL 1.0, 1.1 and 1.2. Plus it supports almost all optional features, including expresison tools, scatter and the recently introduced conditional construct. Related badges have been added to the `README.md` file.

In addition, StreamFlow is used in several European Projects:
 - In the [DeepHealth](https://deephealth-project.eu/) Project it is the workflow engine behind the UniTO OpenDeepHealth platform for multi-tenant Deep Learning pipelines (see for example https://www.micc.unifi.it/icpr2020/wp-content/uploads/demos/s1.1-paper.pdf);
 - In the [ACROSS](https://www.acrossproject.eu/) Project it is part of the architecture of the Multi-level Orchestrator towards Heterogeneous Exascale Computing (related deliverables will be published after acceptance by the European Commission);
 - In the [TEXTAROSSA](https://textarossa.eu/) Project it is one of the programming models and toolchains included in the technological stack (see https://ieeexplore.ieee.org/document/9556353);
 - In the [ADMIRE](https://www.admire-eurohpc.eu/) Project it will be part of a large-scale containerised data analytics application.
 
Finally, it serves as the distributed workflow runtime support for the Jupyter-workflow kernel (see https://www.sciencedirect.com/science/article/pii/S0167739X21003976). Given that, it is ready to be moved in the production-ready implementations of CWL.

**Comment by mr-c** [comment]
@GlassOfWhiskey Thanks for this documentation! I agree; I'll update https://github.com/common-workflow-language/cwl-website/pull/85 accordingly
