### ISSUE TITLE
Problem with docker running as non-root

### ISSUE THREAD

**Issue by libpoet1312** [alpha-unito/streamflow#94]
hello there!.

I am trying to deploy streamflow on openshift and unfortunately the container is not running as root user.
So I am unable to access the built streamflow package in `/root/.local/bin`.

Any ideas on how to install it on the current non-root user?

**Comment by GlassOfWhiskey** [comment]
Hi @libpoet1312,
Thanks for opening an issue.
From the next release, `0.2.0.dev4`, PR #97 installs the `streamflow` package at the system level i nthe `/opt/streamflow` directory.
If you want to experiment with Docker on OpenShift prior to the next release, you can use the `alphaunito/streamflow:cc3a6b7` image i uploaded on the DockerHub.
